### ISSUE TITLE
Is there a way to put the custom API domain for fetching the servers?

### ISSUE THREAD

**Issue by officer47p** [ProtonVPN/ios-mac-app#1]
Well here is the thing:
Currently I'm living in a country in which when I open the app, the initial call for fetching servers is blocked and I should wait for a couple of minutes until it changes the URI to the fallback one.

When I was using Linux and more specifically [this repo](https://github.com/Rafficer/linux-cli-community), I could merge [this PR](https://github.com/Rafficer/linux-cli-community/pull/241/files) in my code and build the project myself, with that the initial call would be successfully fulfilled.

I was looking for a way to do the same thing in the mac version of ProtonVPN so I can avoid the long loading time when I open the app.

I saw [this post](https://protonvpn.com/support/mac-vpn-setup/) about using TunnelBlick but I prefer using the ProtonVPN mac app if it's possible.

Thanks a lot and sorry if it's not the right place to raise this issue 🙏🏻.

**Comment by igorkulman** [comment]
You change change the default url here: https://github.com/ProtonVPN/ios-mac-app/blob/develop/libraries/vpncore/Source/API/Services/DoH.swift#L29
