### ISSUE TITLE
[!] Invalid `Podfile` file: no implicit conversion of nil into String.

### ISSUE THREAD

**Issue by wfs498121294** [ProtonVPN/ios-mac-app#2]
clb@clbdeMac-mini ios-mac-app-develop % pod install

[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/clb/Downloads/ios-mac-app-develop/Podfile:7
 #  -------------------------------------------
 #  def proton_url
 >    'git@' + ENV["PROTON_GIT_URL"]
 #  end
 #  -------------------------------------------

**Comment by jaroslavas** [comment]
There is no need to run `pod install`. You can check how to run a project in the [readme file](https://github.com/ProtonVPN/ios-mac-app#setup).

**Comment by wfs498121294** [comment]
thanks
