### ISSUE TITLE
Code for the latest versions

### ISSUE THREAD

**Issue by fsimonov** [ProtonVPN/ios-mac-app#6]
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
After new designed apps released I decided to check the code for them and didn't find the code for the latest v3.0.0 for MacOS and v3.1.3 for iOS, where can I find it? and seems like iOS app for ProtonMail lags behind in the version as well

**Comment by alonbl** [comment]
The statement is that the source code is 100% open source, and it seems not to be the case.

BTW: The https://protonvpn.com/blog/open-source/ page reference ios old repository and should be fixed.

**Comment by fsimonov** [comment]
Exactly! As I know GitHub repo is only a mirror repo of internal GitLab, hope Proton team will update on this

**Comment by kylekatarnls** [comment]
Yes, it was held for the rebranding and will soon be updated.

**Comment by fsimonov** [comment]
this makes sense

**Comment by alonbl** [comment]
> this makes sense

I do not agree with this :)

I expect source to be released for audit before any binary release push to users.

Nothing should be held back, the complete up-to-date sources should be available at all times.

**Comment by fsimonov** [comment]
I also think so, but since ios builds are not fully reproducible, this delay seems not so crucial and reasonable in case of this rebranding. Seems like other apps are up-to-date

**Comment by deeplow** [comment]
> > 
> 
> I do not agree with this :)
> 
> I expect source to be released for audit before any binary release push to users.
> 
> Nothing should be held back, the complete up-to-date sources should be available at all times.

A new version is out (3.0.2) and still no updated source code:

<img width="621" alt="Screenshot 2022-08-18 at 12 32 07" src="https://user-images.githubusercontent.com/47065258/185386847-07b6d528-706e-476d-93a6-4e7d0c96de6d.png">


Proton should be upfront about distributing proprietary client code to users and also remove this banner from your website as it is misleading marketing:

![Screenshot 2022-08-18 at 12-43-45 Proton VPN Secure and Free VPN service for protecting your privacy](https://user-images.githubusercontent.com/47065258/185386741-a58384b4-d2a9-4d43-a685-ff32525b1851.png)
